# Header
menu:
  Home: /
  Music: /music
  About: /about
  
  # Contact: /contact

# Favicon
favicon_url: images/mine.webp

# Default Image for Posts
default_cover_image: images/default.jpg

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
email_url: ratears.life@outlook.com
weixin_url: https://cdn.jsdelivr.net/gh/sonzonzy/image-hosting@main/blog-img-bed/4a961d5ae9082c7da23b73faa24862b.5q085oeibw00.webp
blog_url: dev.ratears.life
# twitter_url: https://twitter.com/?lang=en
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# linkedin_url: https://www.linkedin.com/
# # dribbble_url:
# github_url: https://github.com/ratears
# googleplus_url:
# behance_url:
# fivehundredpx_url:

# Disqus comments
disqus_shortname:
